"""Init

Revision ID: 26eb0fbb856e
Revises:
Create Date: 2022-07-29 22:54:27.039713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26eb0fbb856e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    map_object_event_status = op.create_table(
        'map_object_event_status',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_object_event_status_name'), 'map_object_event_status', ['name'], unique=True)

    op.bulk_insert(
        map_object_event_status,
        [
            {'name': 'neutral'},
            {'name': 'need_votes'},
            {'name': 'need_attention'},
            {'name': 'updated'},
            {'name': 'new'},
            {'name': '_active (not_used! calculated by sqlalchemy model)'}
        ]
    )

    map_object_tag = op.create_table(
        'map_object_tag',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['map_object_tag.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_map_object_tag', 'map_object_tag', ['name', 'parent_id'], unique=True)

    op.bulk_insert(
        map_object_tag,
        [
            {'id': 1, 'name': 'Организации', 'parent_id': None},
            {'id': 2, 'name': 'Достопримечательности', 'parent_id': None},
            {'id': 3, 'name': 'Видеокамеры', 'parent_id': None},

            {'id': 4, 'name': 'Общепит', 'parent_id': 1},
            {'id': 5, 'name': 'Кафе', 'parent_id': 4},
            {'id': 6, 'name': 'Рестораны', 'parent_id': 4},
            {'id': 7, 'name': 'Бары', 'parent_id': 4},

            {'id': 8, 'name': 'Магазины', 'parent_id': 1},
            {'id': 9, 'name': 'Продукты', 'parent_id': 8},
            {'id': 10, 'name': 'Одежда', 'parent_id': 8},
            {'id': 11, 'name': 'Рыбацкие принадлежности', 'parent_id': 8},

            {'id': 12, 'name': 'Красота', 'parent_id': 1},
            {'id': 13, 'name': 'Парикмахерские', 'parent_id': 12},
            {'id': 14, 'name': 'Ноготочки', 'parent_id': 12},

            {'id': 15, 'name': 'Для животных', 'parent_id': 1},
            {'id': 16, 'name': 'Аптеки', 'parent_id': 15},
            {'id': 17, 'name': 'Продукты', 'parent_id': 15},
            {'id': 18, 'name': 'Клиники', 'parent_id': 15},

            {'id': 19, 'name': 'Памятник', 'parent_id': 2},
            {'id': 20, 'name': 'Прогулка на природе', 'parent_id': 2},
            {'id': 21, 'name': 'Прогулка по городу', 'parent_id': 2},
            {'id': 22, 'name': 'Пилон!!!', 'parent_id': 2},
        ]
    )

    op.create_table(
        'map_object',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('map_object_type', sa.Enum('event', 'organization', 'attraction', name='mapobjecttype'), nullable=True),
        sa.Column('name', sa.String(length=512), nullable=False),
        sa.Column('description', sa.String(length=1024), nullable=True),
        sa.Column('source_url', sa.String(length=1024), nullable=True),
        sa.Column('address', sa.String(length=512), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_object_name'), 'map_object', ['name'], unique=True)

    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('full_name', sa.String(length=512), nullable=True),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('hashed_password', sa.String(length=1024), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_table(
        'map_object_attraction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['map_object.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'map_object_event',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('start_datetime', sa.DateTime(), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('status_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['status_id'], ['map_object_event_status.id'], ),
        sa.ForeignKeyConstraint(['id'], ['map_object.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'map_object_organization',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contacts', sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['map_object.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'map_object_tag_mapping',
        sa.Column('map_object_id', sa.Integer(), nullable=False),
        sa.Column('map_object_tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['map_object_id'], ['map_object.id'], ),
        sa.ForeignKeyConstraint(['map_object_tag_id'], ['map_object_tag.id'], ),
        sa.PrimaryKeyConstraint('map_object_id', 'map_object_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index('uix_map_object_tag', table_name='map_object_tag')
    op.drop_index(op.f('ix_map_object_event_status_name'), table_name='map_object_event_status')
    op.drop_index(op.f('ix_map_object_name'), table_name='map_object')

    op.drop_table('map_object_tag_mapping')
    op.drop_table('map_object_organization')
    op.drop_table('map_object_event')
    op.drop_table('map_object_attraction')
    op.drop_table('map_object_tag')

    op.drop_table('map_object')
    op.drop_table('user')

    op.drop_table('map_object_event_status')
    # ### end Alembic commands ###
