"""Add VK Column

Revision ID: 374f8414ca84
Revises: 3795bf61e88d
Create Date: 2022-08-16 12:39:28.005329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '374f8414ca84'
down_revision = '3795bf61e88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_object', sa.Column('source_url_vk', sa.String(length=1024), nullable=True))
    op.add_column('map_object', sa.Column('source_id_vk', sa.Integer(), nullable=True))
    op.drop_column('map_object', 'source_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_object', sa.Column('source_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=True))
    op.drop_column('map_object', 'source_id_vk')
    op.drop_column('map_object', 'source_url_vk')
    # ### end Alembic commands ###
