"""AddFavorites

Revision ID: 3795bf61e88d
Revises: 26eb0fbb856e
Create Date: 2022-08-07 20:34:21.541788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3795bf61e88d'
down_revision = '26eb0fbb856e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'favorites',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('map_object_id', sa.Integer(), nullable=False),
        sa.Column('date_start', sa.Date(), nullable=False),
        sa.Column('date_end', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['map_object_id'], ['map_object.id'], name=op.f('fk_favorites_map_object_id_map_object')),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favorites_user_id_user')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
