"""Initial Migration

Revision ID: 4db82544a3dd
Revises: 
Create Date: 2022-07-15 02:08:45.839654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db82544a3dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_type', sa.Enum('event', 'vacancy', 'service', 'ad', 'news', name='posttype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('friendly_name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_name'), 'subscription', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('map_post_subscription',
    sa.Column('post', sa.Integer(), nullable=False),
    sa.Column('subscription', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.ForeignKeyConstraint(['subscription'], ['subscription.id'], ),
    sa.UniqueConstraint('subscription', 'post')
    )
    op.create_table('postad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('contacts', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('contacts', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postnews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('contacts', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('contacts', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postvacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=1024), nullable=True),
    sa.Column('organization', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('contacts', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postvacancy')
    op.drop_table('postservice')
    op.drop_table('postnews')
    op.drop_table('postevent')
    op.drop_table('postad')
    op.drop_table('map_post_subscription')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subscription_name'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_table('post')
    # ### end Alembic commands ###
