"""VK Auth

Revision ID: 5fda91e1d29e
Revises: 374f8414ca84
Create Date: 2022-08-17 13:06:45.770394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fda91e1d29e'
down_revision = '374f8414ca84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'v_k_user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uid', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=512), nullable=False),
        sa.Column('last_name', sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_v_k_user'))
    )
    op.create_index(op.f('ix_v_k_user_uid'), 'v_k_user', ['uid'], unique=True)
    op.add_column('user', sa.Column('vk_uid', sa.Integer(), nullable=True))
    op.alter_column(
        'user',
        'hashed_password',
        existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
        nullable=True
    )
    op.create_index(op.f('ix_user_vk_uid'), 'user', ['vk_uid'], unique=True)
    op.create_foreign_key(op.f('fk_user_vk_uid_v_k_user'), 'user', 'v_k_user', ['vk_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_vk_uid_v_k_user'), 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_vk_uid'), table_name='user')
    op.alter_column(
        'user',
        'hashed_password',
        existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
        nullable=False
    )
    op.drop_column('user', 'vk_uid')
    op.drop_index(op.f('ix_v_k_user_uid'), table_name='v_k_user')
    op.drop_table('v_k_user')
    # ### end Alembic commands ###
