"""first revision

Revision ID: 779e672f9b95
Revises: 
Create Date: 2022-06-19 12:23:03.654162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779e672f9b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    # ### end Alembic commands ###
