"""ID Post VK

Revision ID: d76ebb403c28
Revises: 5fda91e1d29e
Create Date: 2022-08-17 15:11:57.580154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76ebb403c28'
down_revision = '5fda91e1d29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_object', sa.Column('post_id_vk', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_object', 'post_id_vk')
    # ### end Alembic commands ###
