version: "3.9"
services:

  db:
      image: mysql:5.7
      container_name: zar_aggregator_db
      environment:
          MYSQL_ROOT_PASSWORD: "RootPassword"
          MYSQL_DATABASE: "app_db"
          MYSQL_USER: "db_user"
          MYSQL_PASSWORD: "AdMiN"
      ports:
        - "3306:3306"
      volumes:
          - /var/lib/mysql
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
          
  backend:
      image: "zar_aggregator_back"
      ports:
          - "8000:8000"
          - "443:443"
          - "222:22"
          - "36723:36723"
          - "54982:54982" 
          - "80:80"
      env_file:
          - ../.env
      build:
        context: ../
        dockerfile: backend.dockerfile
        args:
            INSTALL_DEV: "false"
      depends_on:
          - db # старт после старта контейнера db